version: '3.7'
services:
  routr:
    #build:
    #  context: .
    image: fonoster/routr:latest
    depends_on: [redis]
    environment:
      DATA_SOURCE_PROVIDER: redis_data_provider
      DATA_SOURCE_PARAMETERS: host=redis,port=6379
    ports:
      - '5060:5060'
      - '5060:5060/udp'
      - '5061:5061'
      - '5062:5062'
      - '5063:5063'
      - '4567:4567'
  redis:
    image: redis:6.0.3-alpine
    command: ['redis-server', '--appendonly', 'yes']
    hostname: redis
    ports: 
      - '6379:6379'
