- apiVersion: v1beta1
  kind: Agent
  metadata:
    name: Alarm Receiver
  spec:
    credentials:
      username: 'alarm-test'
      secret: '85GSE2ZV6qypd8'
    domains: [scaipcd.camanio.com]
- apiVersion: v1beta1
  kind: Agent
  metadata:
    name: Alarm Sender
  spec:
    credentials:
      username: '11011018'
      secret: '85GSE2ZV6qypd8'
    domains: [scaipcd.camanio.com]
