- apiVersion: v1beta1
  kind: Domain
  metadata:
    name: Local SIP Server
  spec:
    context:
      domainUri: sip.local
      egressPolicy:
        rule: .{5,}             # Egress only if callee's aor len is 5 or more
        numberRef: dd76afc94b
- apiVersion: v1beta1
  kind: Domain
  metadata:
    name: Local SIP Server 2
  spec:
    context:
      domainUri: sip2.local