- apiVersion: v1beta1
  kind: Number
  metadata:
    ref: dd76afc94b
    gwRef: gw50a1a4ca
    geoInfo:                  # Replace this using your DID's info
      city: City, State
      country: Country
      countryISOCode: US
  spec:
    location:
      # Use your DID number in E164 format
      # This is not a real number, just an example :)
      telUrl: 'tel:+19198972120'        
      aorLink: 'sip:1001@sip.local'
