# Peers and Agents can register in Sip I/O location service
- apiVersion: v1beta1
  kind: Peer
  metadata:
    name: Asterisk PBX
  spec:
    credentials:
      username: ast
      secret: 'changeit'
